create database bdblogforaneo;

USE bdblogforaneo;
CREATE TABLE USUARIO
(

IDUSUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO_PATERNO VARCHAR(50) NOT NULL,
APELLIDO_MATERNO VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE,
USERNAME VARCHAR(50) NOT NULL,
CONTRASENA VARCHAR(50) NOT NULL,
CORREO VARCHAR(70) NOT NULL,
IMAGEN VARCHAR(200) default NULL,
FECHA_CREACION DATE
 
);

ALTER TABLE USUARIO MODIFY IMAGEN VARCHAR(200) default null;

INSERT INTO USUARIO
VALUES (1, 'Regina', 'Rodriguez', 'Campo Garrido', 
'2003-10-11', 'reginarcg', 'Prueba_1', 'regina_rcg@outlook.com',
'imagenDemonoChino.png',  CURDATE());

CREATE TABLE CAT_ESTATUS(
IDESTATUS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ACTIVO BOOL,
ELIMINADO BOOL,
BLOQUEADO BOOL
);

insert into CAT_ESTATUS values(1, '1', '0', '0');
insert into CAT_ESTATUS values(2, '0', '1', '0');
insert into CAT_ESTATUS values(3, '0', '0', '1');
select*from CAT_ESTATUS;

CREATE TABLE PUBLICACION(
IDPUBLICACION INT PRIMARY KEY NOT NULL auto_increment,
TITULO VARCHAR (45),
MEDIA VARCHAR(50),
CONTENIDO VARCHAR(500),
FECHA_POST DATE
);
CREATE TABLE PUBLICACION_CATEGORIA(
IDCAT_PUB INT PRIMARY KEY NOT NULL AUTO_INCREMENT

);

select * from PUBLICACION_CATEGORIA;

CREATE TABLE CAT_CATEGORIAS(
IDCATEGORIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE_CATERGORIAS VARCHAR (45)
);

ALTER TABLE USUARIO
    ADD COLUMN ID_ESTATUS INT,
    ADD CONSTRAINT `FK_USUARIO_ID_ESTATUS` 
    FOREIGN KEY (ID_ESTATUS)
        REFERENCES CAT_ESTATUS(IDESTATUS);

ALTER TABLE PUBLICACION
    ADD COLUMN ID_USUARIO INT,
    ADD CONSTRAINT `FK_PUBLICACION_ID_USUARIO` 
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE PUBLICACION
    ADD COLUMN ID_PUB_STATUS INT,
    ADD CONSTRAINT `FK_PUBLICACION_ID_STATUS` 
    FOREIGN KEY (ID_PUB_STATUS)
        REFERENCES CAT_ESTATUS(IDESTATUS);
        
ALTER TABLE PUBLICACION_CATEGORIA
    ADD COLUMN ID_PUBLICACION INT,
    ADD CONSTRAINT `FK_PUBLICACION_CATEGORIA_ID_PUBLICACION` 
    FOREIGN KEY (ID_PUBLICACION)
        REFERENCES PUBLICACION(IDPUBLICACION);
        
        
ALTER TABLE PUBLICACION_CATEGORIA
    ADD COLUMN ID_CATEGORIA INT,
    ADD CONSTRAINT `FK_PUBLICACION_CATEGORIA_ID_CATEGORIA` 
    FOREIGN KEY (ID_CATEGORIA)
	REFERENCES CAT_CATEGORIAS(IDCATEGORIA);

select * from USUARIO;


select* from PUBLICACION;

UPDATE USUARIO 
SET ID_ESTATUS = 1
WHERE IDUSUARIO = 1;
SELECT * FROM CAT_CATEGORIAS;

SELECT p.IDPUBLICACION, p.TITULO, p.CONTENIDO, p.FECHA_POST, p.MEDIA, u.USERNAME,
        GROUP_CONCAT(c.NOMBRE_CATERGORIAS SEPARATOR ', ') AS CATEGORIAS, p.ID_USUARIO
        FROM PUBLICACION p 
        JOIN USUARIO u ON p.ID_USUARIO = u.IDUSUARIO 
        JOIN PUBLICACION_CATEGORIA cp ON p.IDPUBLICACION = cp.ID_PUBLICACION 
        JOIN CAT_CATEGORIAS c ON cp.ID_CATEGORIA = c.IDCATEGORIA
        WHERE p.ID_PUB_STATUS = 1  
        GROUP BY p.IDPUBLICACION
        ORDER BY p.FECHA_POST DESC